<a href="https://colab.research.google.com/github/pedroedu02/Challenge3_PosTech/blob/main/exploracao_CamadaSilver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!pip install s3fs -q

import pandas as pd

AWS_ACCESS_KEY_ID = "ASIATAWZKUZ53XILYIWT"
AWS_SECRET_ACCESS_KEY = "7hC6minDvPJdo/kBch/xE8d7SvcUSmI7FVml3mpn"
AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjECYaCXVzLXdlc3QtMiJHMEUCIGthW6cG5FJUMVVHmpYUutCNuri6V51uAym4acQOT7wFAiEApReo4EI3CSGgGXwrgn2WoP/Dg5WoXpdYMuFz2P1QQCsqugII7///////////ARADGgwyMDc2ODc5NTE5OTUiDEZM8yc4GJofvFVyZCqOApRNAbgEWRccKF0/hHScAglky5wMebSAVQgZbDgz4SWLCFtfOMkPHX94KyPHcXw35z2RYdPqX/ttaVMTPZJhgZgOd+mq+Z6s1JEGg5FUdDovjrtwKhyIqtnYpG7h5TRLV0quCD7hxkB3rm1HeTCvRx6zDTd0dJObfGY5K7Qz6//8PIWXUBnuhGs2PdrvxDhbn8J6y2yLf2HUiYy3bkEpTpLOYMk8pP2HWhoBPk3VwaYiuizMbPGUAIqtqGoqNwiopLNQO71Ms2qmNtCat61FBNgr1jmeZ8XKBZa423402XCc/nsgQpEkvwOrspwjchowKuz5/Pmn5mgI3s5iarSvUXwgIJdxwBB1q28EHsfF6TCl1aHVBjqdAZnCrPN/7ORiWnjhC7T3RKrFaldog8YCBhbIBATmGfV2PpXh4y8gm9c4Re+AE31tul8TUQq9Ry75wV8MASV1mZS8t1i3oXKqOuk+eR7G7AY/4fnpgChlrV3ZdqBTXfMO4kg0uZWZB8UKOTcBQNc2Bcs6LNDDcO7N48P1R7GUPff4dIZhbi0NgO2gxV5wYcAUVziy5GxtTl1NiojMgKg="

storage_options = {
    "key": AWS_ACCESS_KEY_ID,
    "secret": AWS_SECRET_ACCESS_KEY,
    "token": AWS_SESSION_TOKEN,
}

BUCKET = "tech-challeng-3-pedrogarcia-rm374179"
CAMINHO_SILVER = f"s3://{BUCKET}/Silver/state_of_data"

df_silver = pd.read_parquet(CAMINHO_SILVER, engine="pyarrow", storage_options=storage_options)
print(f"Silver carregada: {df_silver.shape[0]} linhas x {df_silver.shape[1]} colunas")

Silver carregada: 14002 linhas x 17 colunas

In [13]:
df_silver.dtypes.to_frame(name="tipo")

                                    tipo
id                                object
idade                             object
genero                            object
regiao                            object
nivel_ensino                      object
cargo_atual                       object
senioridade                       object
faixa_salarial                    object
exp_dados                         object
modelo_trabalho                   object
linguagem_preferida               object
cloud_dia_a_dia                   object
ferramenta_bi_dia_a_dia           object
tipo_uso_ia_generativa_empresa    object
uso_chatgpt_copilot               object
senioridade_comparavel            object
ano_pesquisa                    category

In [14]:
df_silver["ano_pesquisa"].value_counts().sort_index()

ano_pesquisa
2023         5293
2024         5215
2025-2026    3494
Name: count, dtype: int64

In [15]:
duplicadas = df_silver.duplicated().sum()
print(f"Linhas duplicadas na Silver: {duplicadas}")
assert duplicadas == 0, "Não deveria haver duplicatas na Silver!"
print("OK - nenhuma duplicata encontrada, como esperado.")

Linhas duplicadas na Silver: 0
OK - nenhuma duplicata encontrada, como esperado.

**Validação:** os totais batem com o esperado após a limpeza aplicada no Glue Job
(remoção de duplicatas e de linha 100% vazia): 2023 = 5.293, 2024 = 5.215, 2025-2026 = 3.494.

In [16]:
completude = (1 - df_silver.isna().mean()) * 100
completude.sort_values(ascending=False).round(1).to_frame(name="pct_preenchido")

                                pct_preenchido
id                                       100.0
idade                                    100.0
genero                                   100.0
nivel_ensino                             100.0
ano_pesquisa                             100.0
regiao                                    97.2
exp_dados                                 91.7
modelo_trabalho                           91.7
faixa_salarial                            91.7
cargo_atual                               72.7
senioridade                               72.7
senioridade_comparavel                    72.7
ferramenta_bi_dia_a_dia                   67.8
uso_chatgpt_copilot                       67.8
tipo_uso_ia_generativa_empresa            67.8
cloud_dia_a_dia                           66.4
linguagem_preferida                       66.2

**Leitura:** `id`, `idade`, `genero`, `regiao`, `nivel_ensino` e `ano_pesquisa` têm
preenchimento próximo de 100% (perguntas obrigatórias no início do formulário).
Campos como `tipo_uso_ia_generativa_empresa` e `uso_chatgpt_copilot` têm mais nulo —
consistente com serem perguntas de blocos mais específicos, respondidas por menos gente.

In [17]:
print("--- Checagem 1: erro 'R$ 3000' foi corrigido? ---")
tem_erro_3000 = df_silver["faixa_salarial"].astype(str).str.contains("R\$ 3000", na=False).sum()
print(f"Registros com o erro antigo: {tem_erro_3000} (esperado: 0)")

print()
print("--- Checagem 2: erro 'R$ 101' foi desconsiderado (virou nulo)? ---")
tem_erro_101 = df_silver["faixa_salarial"].astype(str).str.contains("R\$ 101", na=False).sum()
print(f"Registros com o erro antigo: {tem_erro_101} (esperado: 0)")

print()
print("--- Checagem 3: categoria corrigida existe? ---")
print(df_silver["faixa_salarial"].value_counts().filter(like="30.000"))

--- Checagem 1: erro 'R$ 3000' foi corrigido? ---
Registros com o erro antigo: 0 (esperado: 0)

--- Checagem 2: erro 'R$ 101' foi desconsiderado (virou nulo)? ---
Registros com o erro antigo: 0 (esperado: 0)

--- Checagem 3: categoria corrigida existe? ---
faixa_salarial
de R$ 25.001/mês a R$ 30.000/mês    422
Name: count, dtype: int64

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:7: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:7: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipykernel_1228/2573765922.py:2: SyntaxWarning: invalid escape sequence '\$'
  tem_erro_3000 = df_silver["faixa_salarial"].astype(str).str.contains("R\$ 3000", na=False).sum()
/tmp/ipykernel_1228/2573765922.py:7: SyntaxWarning: invalid escape sequence '\$'
  tem_erro_101 = df_silver["faixa_salarial"].astype(str).str.contains("R\$ 101", na=False).sum()

In [18]:
comparacao = pd.crosstab(df_silver["senioridade"], df_silver["senioridade_comparavel"], dropna=False)
comparacao

senioridade_comparavel  Júnior  Pleno  Sênior   NaN
senioridade
Especialista/Staff+          0      0     349     0
Júnior                    2432      0       0     0
Pleno                        0   3543       0     0
Sênior                       0      0    3849     0
NaN                          0      0       0  3829

**Validação:** confirma que todo registro "Especialista/Staff+" (categoria só de
2025-2026) foi agrupado em "Sênior" na coluna `senioridade_comparavel`, sem alterar a
coluna original `senioridade`.

In [19]:
for ano in sorted(df_silver["ano_pesquisa"].unique()):
    print(f"--- Amostra {ano} ---")
    display(df_silver[df_silver["ano_pesquisa"] == ano][
        ["idade","genero","regiao","cargo_atual","senioridade","faixa_salarial","modelo_trabalho"]
    ].head(3))
    print()

--- Amostra 2023 ---

,idade,genero,regiao,cargo_atual,senioridade,faixa_salarial,modelo_trabalho
0,30,Masculino,Sudeste,Engenheiro de Dados/Arquiteto de Dados/Data En...,Pleno,de R$ 8.001/mês a R$ 12.000/mês,Modelo 100% remoto
1,27,Masculino,Norte,Analista de Dados/Data Analyst,Pleno,de R$ 6.001/mês a R$ 8.000/mês,Modelo 100% remoto
2,28,Masculino,Sudeste,Engenheiro de Dados/Arquiteto de Dados/Data En...,Sênior,de R$ 12.001/mês a R$ 16.000/mês,Modelo híbrido flexível (o funcionário tem lib...

--- Amostra 2024 ---

,idade,genero,regiao,cargo_atual,senioridade,faixa_salarial,modelo_trabalho
5293,18,Masculino,Sudeste,Analista de BI/BI Analyst,Júnior,de R$ 6.001/mês a R$ 8.000/mês,Modelo 100% presencial
5294,19,Masculino,Centro-oeste,Analista de Dados/Data Analyst,Júnior,de R$ 3.001/mês a R$ 4.000/mês,Modelo 100% remoto
5295,21,Masculino,Sudeste,Engenheiro de Dados/Data Engineer/Data Architect,Júnior,de R$ 4.001/mês a R$ 6.000/mês,Modelo 100% remoto

--- Amostra 2025-2026 ---

,idade,genero,regiao,cargo_atual,senioridade,faixa_salarial,modelo_trabalho
10508,33,Feminino,Sudeste,Analista de Dados/Data Analyst,Pleno,de R$ 8.001/mês a R$ 12.000/mês,Modelo 100% presencial
10509,24,Masculino,Sudeste,Analytics Engineer,Especialista/Staff+,de R$ 12.001/mês a R$ 16.000/mês,Modelo híbrido flexível (o funcionário tem lib...
10510,25,Masculino,Sudeste,Analista de Dados/Data Analyst,Júnior,de R$ 3.001/mês a R$ 4.000/mês,Modelo híbrido com dias fixos de trabalho pres...

## 8. Resumo

In [20]:
print(f"Total de linhas na Silver: {len(df_silver)}")
print(f"Total de colunas: {len(df_silver.columns)}")
print(f"Anos presentes: {sorted(df_silver['ano_pesquisa'].unique())}")
print(f"Duplicatas: {df_silver.duplicated().sum()} (esperado: 0)")
print(f"Erros de digitação conhecidos ainda presentes: {tem_erro_3000 + tem_erro_101} (esperado: 0)")
print()
print("Conclusão: a camada Silver está íntegra e pronta para alimentar a camada Gold.")

Total de linhas na Silver: 14002
Total de colunas: 17
Anos presentes: ['2023', '2024', '2025-2026']
Duplicatas: 0 (esperado: 0)
Erros de digitação conhecidos ainda presentes: 0 (esperado: 0)

Conclusão: a camada Silver está íntegra e pronta para alimentar a camada Gold.