<a href="https://colab.research.google.com/github/pedroedu02/Challenge3_PosTech/blob/main/exploracao_Gold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
!pip install s3fs -q

import pandas as pd

AWS_ACCESS_KEY_ID = "ASIATAWZKUZ53XILYIWT"
AWS_SECRET_ACCESS_KEY = "7hC6minDvPJdo/kBch/xE8d7SvcUSmI7FVml3mpn"
AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjECYaCXVzLXdlc3QtMiJHMEUCIGthW6cG5FJUMVVHmpYUutCNuri6V51uAym4acQOT7wFAiEApReo4EI3CSGgGXwrgn2WoP/Dg5WoXpdYMuFz2P1QQCsqugII7///////////ARADGgwyMDc2ODc5NTE5OTUiDEZM8yc4GJofvFVyZCqOApRNAbgEWRccKF0/hHScAglky5wMebSAVQgZbDgz4SWLCFtfOMkPHX94KyPHcXw35z2RYdPqX/ttaVMTPZJhgZgOd+mq+Z6s1JEGg5FUdDovjrtwKhyIqtnYpG7h5TRLV0quCD7hxkB3rm1HeTCvRx6zDTd0dJObfGY5K7Qz6//8PIWXUBnuhGs2PdrvxDhbn8J6y2yLf2HUiYy3bkEpTpLOYMk8pP2HWhoBPk3VwaYiuizMbPGUAIqtqGoqNwiopLNQO71Ms2qmNtCat61FBNgr1jmeZ8XKBZa423402XCc/nsgQpEkvwOrspwjchowKuz5/Pmn5mgI3s5iarSvUXwgIJdxwBB1q28EHsfF6TCl1aHVBjqdAZnCrPN/7ORiWnjhC7T3RKrFaldog8YCBhbIBATmGfV2PpXh4y8gm9c4Re+AE31tul8TUQq9Ry75wV8MASV1mZS8t1i3oXKqOuk+eR7G7AY/4fnpgChlrV3ZdqBTXfMO4kg0uZWZB8UKOTcBQNc2Bcs6LNDDcO7N48P1R7GUPff4dIZhbi0NgO2gxV5wYcAUVziy5GxtTl1NiojMgKg="


storage_options = {
    "key": AWS_ACCESS_KEY_ID,
    "secret": AWS_SECRET_ACCESS_KEY,
    "token": AWS_SESSION_TOKEN,
}

BUCKET = "tech-challeng-3-pedrogarcia-rm374179"
TABELAS_GOLD = ["mercado", "remuneracao", "tecnologias", "ia", "diversidade", "trabalho"]

gold = {}
for nome in TABELAS_GOLD:
    caminho = f"s3://{BUCKET}/Gold/{nome}"
    gold[nome] = pd.read_parquet(caminho, engine="pyarrow", storage_options=storage_options)
    print(f"gold_{nome}: {gold[nome].shape[0]} linhas x {gold[nome].shape[1]} colunas")

gold_mercado: 1885 linhas x 6 colunas
gold_remuneracao: 2429 linhas x 6 colunas
gold_tecnologias: 3303 linhas x 6 colunas
gold_ia: 1074 linhas x 5 colunas
gold_diversidade: 1106 linhas x 6 colunas
gold_trabalho: 495 linhas x 5 colunas

In [24]:
for nome, df in gold.items():
    print(f"--- gold_{nome} ---")
    print(list(df.columns))
    print()

--- gold_mercado ---
['regiao', 'senioridade_comparavel', 'cargo_atual', 'nivel_ensino', 'total_profissionais', 'ano_pesquisa']

--- gold_remuneracao ---
['cargo_atual', 'senioridade_comparavel', 'regiao', 'faixa_salarial', 'total_profissionais', 'ano_pesquisa']

--- gold_tecnologias ---
['categoria', 'tecnologia', 'cargo_atual', 'senioridade_comparavel', 'total_mencoes', 'ano_pesquisa']

--- gold_ia ---
['cargo_atual', 'senioridade_comparavel', 'uso_chatgpt_copilot', 'total_profissionais', 'ano_pesquisa']

--- gold_diversidade ---
['genero', 'senioridade_comparavel', 'cargo_atual', 'regiao', 'total_profissionais', 'ano_pesquisa']

--- gold_trabalho ---
['modelo_trabalho', 'faixa_salarial', 'senioridade_comparavel', 'total_profissionais', 'ano_pesquisa']

In [25]:
df = gold["mercado"]

total_por_ano = df.groupby("ano_pesquisa")["total_profissionais"].sum()
print("Total de profissionais por ano:")
print(total_por_ano)

Total de profissionais por ano:
ano_pesquisa
2023         5293
2024         5215
2025-2026    3494
Name: total_profissionais, dtype: int64

/tmp/ipykernel_1228/3563646449.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_por_ano = df.groupby("ano_pesquisa")["total_profissionais"].sum()

In [26]:
senioridade_ano = (
    df.groupby(["ano_pesquisa", "senioridade_comparavel"])["total_profissionais"]
      .sum()
      .unstack()
)
senioridade_pct = senioridade_ano.div(senioridade_ano.sum(axis=1), axis=0).mul(100).round(1)
senioridade_pct

/tmp/ipykernel_1228/2206201629.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["ano_pesquisa", "senioridade_comparavel"])["total_profissionais"]

senioridade_comparavel  Júnior  Não informado  Pleno  Sênior
ano_pesquisa
2023                      19.8           27.1   26.3    26.8
2024                      16.6           26.8   26.4    30.1
2025-2026                 14.8           28.4   22.2    34.5

In [27]:
df = gold["remuneracao"]

faixa_top = (
    df.groupby(["ano_pesquisa", "faixa_salarial"])["total_profissionais"]
      .sum()
      .reset_index()
      .sort_values(["ano_pesquisa", "total_profissionais"], ascending=[True, False])
      .groupby("ano_pesquisa")
      .head(1)
)
faixa_top

/tmp/ipykernel_1228/2162098387.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["ano_pesquisa", "faixa_salarial"])["total_profissionais"]
/tmp/ipykernel_1228/2162098387.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("ano_pesquisa")

   ano_pesquisa                   faixa_salarial  total_profissionais
12         2023  de R$ 8.001/mês a R$ 12.000/mês                 1026
25         2024  de R$ 8.001/mês a R$ 12.000/mês                 1080
38    2025-2026  de R$ 8.001/mês a R$ 12.000/mês                  707

In [28]:
df = gold["tecnologias"]

top_linguagens = (
    df[df["categoria"] == "linguagem"]
    .groupby(["ano_pesquisa", "tecnologia"])["total_mencoes"]
    .sum()
    .reset_index()
    .sort_values(["ano_pesquisa", "total_mencoes"], ascending=[True, False])
)
top_linguagens.groupby("ano_pesquisa").head(3)

/tmp/ipykernel_1228/1047875994.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["ano_pesquisa", "tecnologia"])["total_mencoes"]
/tmp/ipykernel_1228/1047875994.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  top_linguagens.groupby("ano_pesquisa").head(3)

    ano_pesquisa tecnologia  total_mencoes
43          2023     Python           3299
46          2023          R            228
51          2023        SQL             74
110         2024     Python           3040
113         2024          R            186
118         2024        SQL             66
177    2025-2026     Python           1928
185    2025-2026        SQL           1763
180    2025-2026          R            294

In [29]:
df = gold["ia"]

def eh_nao_usa(valor):
    return "Não utilizo" in str(valor)

df["nao_usa"] = df["uso_chatgpt_copilot"].apply(eh_nao_usa)

# Compativel com qualquer versao de pandas (evita o parametro include_groups,
# disponivel so a partir do pandas 2.2)
nao_usa_por_ano = df[df["nao_usa"]].groupby("ano_pesquisa")["total_profissionais"].sum()
total_por_ano = df.groupby("ano_pesquisa")["total_profissionais"].sum()

resumo_ia = pd.DataFrame({
    "nao_usa": nao_usa_por_ano,
    "total": total_por_ano,
}).fillna(0)
resumo_ia["pct_nao_usa"] = (resumo_ia["nao_usa"] / resumo_ia["total"] * 100).round(1)
resumo_ia

/tmp/ipykernel_1228/4146857257.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  nao_usa_por_ano = df[df["nao_usa"]].groupby("ano_pesquisa")["total_profissionais"].sum()
/tmp/ipykernel_1228/4146857257.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_por_ano = df.groupby("ano_pesquisa")["total_profissionais"].sum()

              nao_usa  total  pct_nao_usa
ano_pesquisa
2023              744   3772         19.7
2024              236   3617          6.5
2025-2026          44   2105          2.1

In [30]:
df = gold["diversidade"]

genero_ano = (
    df.groupby(["ano_pesquisa", "genero"])["total_profissionais"]
      .sum()
      .unstack()
)
genero_pct = genero_ano.div(genero_ano.sum(axis=1), axis=0).mul(100).round(1)
genero_pct

/tmp/ipykernel_1228/2214618134.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["ano_pesquisa", "genero"])["total_profissionais"]

genero        Feminino  Masculino  Outro  Prefiro não informar
ano_pesquisa
2023              24.4       75.1    0.2                   0.3
2024              23.5       76.1    0.2                   0.3
2025-2026         22.0       77.5    0.2                   0.4

In [31]:
df = gold["trabalho"]

remoto = (
    df[df["modelo_trabalho"] == "Modelo 100% remoto"]
    .groupby("ano_pesquisa")["total_profissionais"]
    .sum()
)
remoto

/tmp/ipykernel_1228/621653635.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("ano_pesquisa")["total_profissionais"]

ano_pesquisa
2023         2201
2024         2221
2025-2026    1281
Name: total_profissionais, dtype: int64

In [32]:
soma_mercado = gold["mercado"]["total_profissionais"].sum()
print(f"Soma de gold_mercado (sem filtro): {soma_mercado}")
print(f"Total esperado (= linhas da Silver, pois mercado não filtra ninguém): 14002")
assert soma_mercado == 14002, "Divergência encontrada!"
print("OK - bate exatamente com o total da Silver.")

Soma de gold_mercado (sem filtro): 14002
Total esperado (= linhas da Silver, pois mercado não filtra ninguém): 14002
OK - bate exatamente com o total da Silver.

## 9. Resumo

In [33]:
print("Tabelas Gold validadas:")
for nome, df in gold.items():
    print(f"  gold_{nome}: {len(df)} linhas, {df['ano_pesquisa'].nunique()} anos")
print()
print("Conclusão: as 6 tabelas Gold estão íntegras, consistentes entre si, e prontas")
print("para alimentar os gráficos e o material executivo (PPTX).")

Tabelas Gold validadas:
  gold_mercado: 1885 linhas, 3 anos
  gold_remuneracao: 2429 linhas, 3 anos
  gold_tecnologias: 3303 linhas, 3 anos
  gold_ia: 1074 linhas, 3 anos
  gold_diversidade: 1106 linhas, 3 anos
  gold_trabalho: 495 linhas, 3 anos

Conclusão: as 6 tabelas Gold estão íntegras, consistentes entre si, e prontas
para alimentar os gráficos e o material executivo (PPTX).